fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    yamlfile: "reidmv/yamlfile"
    filemapper: "adrien/filemapper"
    remote_file: "lwf/remote_file"
  repositories:
    githubreleases:
      repo: "https://github.com/dodevops/puppet-githubreleases"